db.states.drop();
db.states.insert({"name": "Acre", "shortname": "AC"})
db.states.insert({"name": "Alagoas", "shortname": "AL"})
db.states.insert({"name": "Amapá", "shortname": "AP"})
db.states.insert({"name": "Amazonas", "shortname": "AM"})
db.states.insert({"name": "Bahia", "shortname": "BA"})
db.states.insert({"name": "Ceará", "shortname": "CE"})
db.states.insert({"name": "Distrito Federal", "shortname": "DF"})
db.states.insert({"name": "Espírito Santo", "shortname": "ES"})
db.states.insert({"name": "Goiás", "shortname": "GO"})
db.states.insert({"name": "Maranhão", "shortname": "MA"})
db.states.insert({"name": "Mato Grosso", "shortname": "MT"})
db.states.insert({"name": "Mato Grosso do Sul", "shortname": "MS"})
db.states.insert({"name": "Minas Gerais", "shortname": "MG"})
db.states.insert({"name": "Pará", "shortname": "PA"})
db.states.insert({"name": "Paraíba", "shortname": "PB"})
db.states.insert({"name": "Paraná", "shortname": "PR"})
db.states.insert({"name": "Pernambuco", "shortname": "PE"})
db.states.insert({"name": "Piauí", "shortname": "PI"})
db.states.insert({"name": "Rio de Janeiro", "shortname": "RJ"})
db.states.insert({"name": "Rio Grande do Norte", "shortname": "RN"})
db.states.insert({"name": "Rio Grande do Sul", "shortname": "RS"})
db.states.insert({"name": "Rondônia", "shortname": "RO"})
db.states.insert({"name": "Roraima", "shortname": "RR"})
db.states.insert({"name": "Santa Catarina", "shortname": "SC"})
db.states.insert({"name": "São Paulo", "shortname": "SP"})
db.states.insert({"name": "Sergipe", "shortname": "SE"})
db.states.insert({"name": "Tocantins", "shortname": "TO"})